DROP DATABASE IF EXISTS plantsdb;
DROP USER IF EXISTS student;
CREATE DATABASE plantsdb;
CREATE USER student WITH ENCRYPTED PASSWORD 'student';
GRANT ALL PRIVILEGES ON DATABASE plantsdb TO student;
ALTER USER student CREATEDB;
ALTER USER student WITH SUPERUSER;